version: 2
jobs:
  build:
    working_directory: ~/trajminer
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run: sudo pip uninstall pipenv
      - run: pip install pipenv
      - run: pipenv install
      - run: pip install .
  test:
    docker:
      - image: circleci/python:3.6.6
    steps:
      - checkout
      - run:
          name: Test
          command: 'pipenv run python -m pytest ./trajminer'

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master