version: 2
jobs:
  build:
    working_directory: ~/trajminer
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout  
      - run:
          name: Install pipenv
          command: pip install pipenv
      - run: pipenv install
      - run:
          name: Install pytest
          command: pipenv install pytest
      - run:
          name: Install trajminer
          command: pipenv install .
  test:
    docker:
      - image: circleci/python:3.6.7
    steps:
      - checkout
      - run:
          name: Run tests
          command: pipenv run python -m pytest ./trajminer

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build